name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  ubuntu_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: apt
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip curl
    - name: pip
      run: |
        pip3 install .[test]
        pip3 install git+https://github.com/johnwason/simple-launch-process.git
    - name: test
      run: |
        python3 -m pytest -s
  windows_test:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: pip
      run: |
        pip install .[test]
        pip install git+https://github.com/johnwason/simple-launch-process.git
    - name: test
      run: |
        python -m pytest -s

